#[derive(Debug, Copy, Clone)]
pub enum ItemList {
    WoodenSword = 0,
    IronSword = 1,
    GoldenSword = 2,
    DiamondSword = 3,
    WoodenAxe = 4,
    IronAxe = 5,
    GoldenAxe = 6,
    DiamondAxe = 7,
    WoodenPickaxe = 8,
    IronPickaxe = 9,
    GoldenPickaxe = 10,
    DiamondPickaxe = 11,
    WoodenShovel = 12,
    IronShovel = 13,
    GoldenShovel = 14,
    DiamondShovel = 15,
    WoodenHoe = 16,
    IronHoe = 17,
    GoldenHoe = 18,
    DiamondHoe = 19,
    Bow = 20,
    Crossbow = 21,
    Arrow = 22,
    IronChestplate = 23,
    IronLeggings = 24,
    IronHelmet = 25,
    IronBoots = 26,
    GoldenChestplate = 27,
    GoldenLeggings = 28,
    GoldenHelmet = 29,
    GoldenBoots = 30,
    DiamondChestplate = 31,
    DiamondLeggings = 32,
    DiamondHelmet = 33,
    DiamondBoots = 34,
}

impl ItemList {
    pub fn name(&self) -> &'static str {
        match self {
            ItemList::WoodenSword => "Wooden Sword",
            ItemList::IronSword => "Iron Sword",
            ItemList::GoldenSword => "Golden Sword",
            ItemList::DiamondSword => "Diamond Sword",
            ItemList::WoodenAxe => "Wooden Axe",
            ItemList::IronAxe => "Iron Axe",
            ItemList::GoldenAxe => "Golden Axe",
            ItemList::DiamondAxe => "Diamond Axe",
            ItemList::WoodenPickaxe => "Wooden Pickaxe",
            ItemList::IronPickaxe => "Iron Pickaxe",
            ItemList::GoldenPickaxe => "Golden Pickaxe",
            ItemList::DiamondPickaxe => "Diamond Pickaxe",
            ItemList::WoodenShovel => "Wooden Shovel",
            ItemList::IronShovel => "Iron Shovel",
            ItemList::GoldenShovel => "Golden Shovel",
            ItemList::DiamondShovel => "Diamond Shovel",
            ItemList::WoodenHoe => "Wooden Hoe",
            ItemList::IronHoe => "Iron Hoe",
            ItemList::GoldenHoe => "Golden Hoe",
            ItemList::DiamondHoe => "Diamond Hoe",
            ItemList::Bow => "Bow",
            ItemList::Crossbow => "Crossbow",
            ItemList::Arrow => "Arrow",
            ItemList::IronChestplate => "Iron Chestplate",
            ItemList::IronLeggings => "Iron Leggings",
            ItemList::IronHelmet => "Iron Helmet",
            ItemList::IronBoots => "Iron Boots",
            ItemList::GoldenChestplate => "Golden Chestplate",
            ItemList::GoldenLeggings => "Golden Leggings",
            ItemList::GoldenHelmet => "Golden Helmet",
            ItemList::GoldenBoots => "Golden Boots",
            ItemList::DiamondChestplate => "Diamond Chestplate",
            ItemList::DiamondLeggings => "Diamond Leggings",
            ItemList::DiamondHelmet => "Diamond Helmet",
            ItemList::DiamondBoots => "Diamond Boots",
        }
    }

    pub fn id(&self) -> u32 {
       *self as u32
    }
}
