#[derive(Debug, Copy, Clone)]
pub enum ItemList {
    WoodenSword,
    StoneSword,
    IronSword,
    GoldenSword,
    DiamondSword,
    WoodenAxe,
    IronAxe,
    GoldenAxe,
    DiamondAxe,
    WoodenPickaxe,
    IronPickaxe,
    GoldenPickaxe,
    DiamondPickaxe,
    WoodenShovel,
    IronShovel,
    GoldenShovel,
    DiamondShovel,
    WoodenHoe,
    IronHoe,
    GoldenHoe,
    DiamondHoe,
    Bow,
    Crossbow,
    Arrow,
    IronChestplate,
    IronLeggings,
    IronHelmet,
    IronBoots,
    GoldenChestplate,
    GoldenLeggings,
    GoldenHelmet,
    GoldenBoots,
    DiamondChestplate,
    DiamondLeggings,
    DiamondHelmet,
    DiamondBoots,
}

impl ItemList {
    pub fn name(&self) -> &'static str {
        match self {
            ItemList::WoodenSword => "Wooden Sword",
            ItemList::StoneSword => "Stone Sword",
            ItemList::IronSword => "Iron Sword",
            ItemList::GoldenSword => "Golden Sword",
            ItemList::DiamondSword => "Diamond Sword",
            ItemList::WoodenAxe => "Wooden Axe",
            ItemList::IronAxe => "Iron Axe",
            ItemList::GoldenAxe => "Golden Axe",
            ItemList::DiamondAxe => "Diamond Axe",
            ItemList::WoodenPickaxe => "Wooden Pickaxe",
            ItemList::IronPickaxe => "Iron Pickaxe",
            ItemList::GoldenPickaxe => "Golden Pickaxe",
            ItemList::DiamondPickaxe => "Diamond Pickaxe",
            ItemList::WoodenShovel => "Wooden Shovel",
            ItemList::IronShovel => "Iron Shovel",
            ItemList::GoldenShovel => "Golden Shovel",
            ItemList::DiamondShovel => "Diamond Shovel",
            ItemList::WoodenHoe => "Wooden Hoe",
            ItemList::IronHoe => "Iron Hoe",
            ItemList::GoldenHoe => "Golden Hoe",
            ItemList::DiamondHoe => "Diamond Hoe",
            ItemList::Bow => "Bow",
            ItemList::Crossbow => "Crossbow",
            ItemList::Arrow => "Arrow",
            ItemList::IronChestplate => "Iron Chestplate",
            ItemList::IronLeggings => "Iron Leggings",
            ItemList::IronHelmet => "Iron Helmet",
            ItemList::IronBoots => "Iron Boots",
            ItemList::GoldenChestplate => "Golden Chestplate",
            ItemList::GoldenLeggings => "Golden Leggings",
            ItemList::GoldenHelmet => "Golden Helmet",
            ItemList::GoldenBoots => "Golden Boots",
            ItemList::DiamondChestplate => "Diamond Chestplate",
            ItemList::DiamondLeggings => "Diamond Leggings",
            ItemList::DiamondHelmet => "Diamond Helmet",
            ItemList::DiamondBoots => "Diamond Boots",
        }
    }

    pub fn id(&self) -> u32 {
       *self as u32
    }
}
